### ISSUE TITLE
Make README.md more informative and assistive.

### ISSUE THREAD

**Issue by Arna-Maity** [SouravJohar/expense-tracker#8]
Hey @SouravJohar we could add commands on how to install the python package dependencies in the README.md file. This would help the beginners to get started with development faster. Also we could add a requirements.txt file to the project so that pip can automatically use this file to install the necessary dependencies.

**Comment by SouravJohar** [comment]
You're right. It'll be great if you can make those changes and send in a pull request :)

**Comment by Arna-Maity** [comment]
I already did so, and also opened a PR. Please review it and tell me if i need to do any further changes.

**Comment by SouravJohar** [comment]
Thanks. Merged.
